//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public enum nacionalidades {USA,Francia,Inglaterra}
    public enum productor { HarveyWeinstein,StevenSpielberg,IcíarBollaín}
    public partial class pelicula
    {
        [Key][StringLength(10,MinimumLength =10)]
        public string id { get; set; }
        [Display(Name ="Titulo")][StringLength(100,MinimumLength =50)]
        public string Titulo { get; set; }
        public nacionalidades nacionalidad { get; set; }
        public productor productora { get; set; }
        [Required] [Display(Name ="Fecha de Estreno")]
        public System.DateTime fecha { get; set; }
        [Required][StringLength(10,MinimumLength =10)]
        public string id_director { get; set; }
    }
}
